import Login from "@/components/login/Login";
import Head from "next/head";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Login | Travelo</title>
        <meta name="Travelo Login Page" content="Generated by create next app" />
      </Head>
      <Login />
    </>
  );
}
