import HomeContainer from "@/components/containers/HomeContainer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Travelo</title>
        <meta name="Travelo" content="Generated by create next app" />
      </Head>
      <HomeContainer />
    </>
  );
}
